<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <!-- In your own project: <PackageReference Include="Likyly" Version="1.*" /> -->
    <ProjectReference Include="../../src/Likyly/Likyly.csproj" />
  </ItemGroup>

</Project>
